name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install build dependencies
        run: make deps

      - name: Code format
        run: make format && git diff --exit-code

      - name: Code test
        run: make test

      - name: Code lint
        run: make lint
