name: Release
on:
  push:
    tags:
      - v*
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Go setup
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Build project
        run: make build

      - name: Automatic releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: ./bin/*
